spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${collide.turbo.nacos.server.url}
        namespace: public
        username: ${collide.turbo.nacos.server.username}
        password: ${collide.turbo.nacos.server.password}
      config:
        server-addr: ${collide.turbo.nacos.server.url}
        file-extension: properties
        name: ${spring.application.name}