spring:
  autoconfigure:
    exclude: org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration
  cloud:
    nacos:
      username: ${collide.turbo.nacos.server.username}
      password: ${collide.turbo.nacos.server.password}
      discovery:
        server-addr: ${collide.turbo.nacos.server.url}
      config:
        server-addr: ${collide.turbo.nacos.server.url}
        file-extension: properties
        name: ${spring.application.name}