spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9607

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.like.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 点赞模块专用配置
collide:
  like:
    # 防重复点赞时间窗口（秒）
    duplicate-window: 5
    # 批量检查最大数量
    batch-check-max-size: 100
    # 点赞统计同步间隔（分钟）
    stats-sync-interval: 10
    # 热门内容阈值
    hot-threshold: 100
    # 数据清理天数
    cleanup-days: 90