services:
  # Gateway 服务
  collide-gateway:
    build:
      context: .
      dockerfile: collide-gateway/Dockerfile
    image: collide/gateway:latest
    container_name: collide-gateway
    ports:
      - "9501:9501"  # Gateway端口映射
    environment:
      - SERVER_PORT=9501
      - JAVA_OPTS=-Xms256m -Xmx512m -server
    restart: unless-stopped
    depends_on:
      - collide-application
    labels:
      - "com.collide.service=gateway"
      - "com.collide.version=1.0.0"
    networks:
      collide-network:
        ipv4_address: 172.20.2.10

  # Auth 服务
  collide-auth:
    build:
      context: .
      dockerfile: collide-auth/Dockerfile
    image: collide/auth:latest
    container_name: collide-auth
    ports:
      - "9502:9502"  # Auth端口映射
    environment:
      - SERVER_PORT=9502
      - JAVA_OPTS=-Xms256m -Xmx512m -server
    depends_on:
      - collide-application
    labels:
      - "com.collide.service=auth"
      - "com.collide.version=1.0.0"
    networks:
      collide-network:
        ipv4_address: 172.20.2.20

  # Application 服务（业务应用聚合）
  collide-application:
    build:
      context: .
      dockerfile: collide-application/Dockerfile
    image: collide/application:latest
    container_name: collide-application
    ports:
      - "9503:9503"  # Application端口映射
    environment:
      - SERVER_PORT=9503
      - JAVA_OPTS=-Xms512m -Xmx1024m -server
    restart: unless-stopped
    labels:
      - "com.collide.service=application"
      - "com.collide.version=1.0.0"
    networks:
      collide-network:
        ipv4_address: 172.20.2.30

# 使用外部网络
networks:
  collide-network:
    external: true