services:
  # 网关服务
  collide-gateway:
    image: collide-gateway:latest
    container_name: collide-gateway
    network_mode: host
    ports:
      - "${GATEWAY_PORT:-9500}:9500"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./logs/gateway:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9500/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 认证服务
  collide-auth:
    image: collide-auth:latest
    container_name: collide-auth
    network_mode: host
    ports:
      - "${AUTH_PORT:-9501}:9501"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./logs/auth:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9501/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 业务应用服务
  collide-application:
    image: collide-application:latest
    container_name: collide-application
    network_mode: host
    ports:
      - "${BUSINESS_PORT:-9502}:9502"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./logs/business:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9502/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# 网络配置
networks:
  collide-network:
    driver: bridge

# 数据卷配置  
volumes:
  logs:
    driver: local 