spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml

server:
  port: 9603

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.social.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 社交模块专用配置
collide:
  social:
    # 默认分页大小
    default-page-size: 20
    # 最大分页大小
    max-page-size: 100
    # 帖子最大长度
    post-max-length: 2000
    # 互动缓存过期时间（分钟）
    interaction-cache-expire: 30
    # 统计信息缓存过期时间（分钟）
    statistics-cache-expire: 60
    # 热门帖子默认数量
    hot-posts-default-limit: 50
    # 推荐帖子默认数量
    recommend-posts-default-limit: 20 