spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:config.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml   #这里爆红可以直接忽略，没有任何影响

server:
  port: 8086

# Dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20886
  registry:
    address: nacos://${nacos.server.address}
  provider:
    timeout: 10000
    retries: 0

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gig.collide.social.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 社交服务特定配置
collide:
  social:
    # 热度分数计算配置
    hot-score:
      # 点赞权重
      like-weight: 1.0
      # 评论权重
      comment-weight: 2.0
      # 转发权重
      share-weight: 3.0
      # 收藏权重
      favorite-weight: 1.5
      # 时间衰减因子
      time-decay-factor: 0.1
      # 热度更新间隔（分钟）
      update-interval: 30
    
    # 内容审核配置
    content-review:
      # 是否启用自动审核
      auto-review-enabled: true
      # 敏感词检测
      sensitive-word-check: true
      # 图片审核
      image-review: true
      # 视频审核
      video-review: false
    
    # 推送配置
    feed:
      # 时间线缓存时间（分钟）
      timeline-cache-ttl: 60
      # 热门动态缓存时间（分钟）  
      hot-posts-cache-ttl: 30
      # 附近动态搜索半径上限（公里）
      max-nearby-radius: 50
      # 单次查询最大返回数量
      max-page-size: 100

# 日志配置
logging:
  level:
    com.gig.collide.social: DEBUG
    org.apache.dubbo: INFO 