spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9612

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.social.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 社交模块专用配置
collide:
  social:
    # 动态内容最大长度
    max-content-length: 2000
    # 图片最大数量
    max-images: 9
    # 视频文件最大大小（MB）
    max-video-size: 100
    # 热门动态阈值
    hot-threshold: 100
    # 动态流分页大小
    feed-page-size: 20
    # 敏感内容过滤开关
    content-filter-enabled: true 