spring:
  profiles:
    active: local
  application:
    name: collide-search

---
# 本地开发环境配置
spring:
  config:
    activate:
      on-profile: local

server:
  port: 9503

# 数据库配置 - 对齐项目标准
collide:
  turbo:
    mysql:
      url: localhost:3306
      username: root
      password: 123456

# 缓存配置 - 使用标准化配置
cache:
  enabled: true
  default-expire: 3600

# 日志配置
logging:
  level:
    com.gig.collide.search: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.jdbc: DEBUG

---
# Docker环境配置
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

# 数据库配置 - Docker环境
collide:
  turbo:
    mysql:
      url: mysql-service:3306
      username: collide_user
      password: collide_password

logging:
  level:
    root: INFO
    com.gig.collide.search: INFO

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080

# 生产环境数据库配置
collide:
  turbo:
    mysql:
      url: ${DB_HOST:prod-mysql}:${DB_PORT:3306}
      username: ${DB_USERNAME:collide_prod}
      password: ${DB_PASSWORD:prod_password}

logging:
  level:
    root: WARN
    com.gig.collide.search: INFO 