-- 标签主表
CREATE TABLE `tag` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '标签ID（自增主键）',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '最后更新时间',
  `tag_name` varchar(128) NOT NULL COMMENT '标签名称',
  `description` text COMMENT '标签描述',
  `tag_type` varchar(32) NOT NULL DEFAULT 'USER' COMMENT '标签类型（SYSTEM系统，USER用户，CONTENT内容，CATEGORY分类，PERSONAL个人，TRENDING热门）',
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '标签状态（ACTIVE正常，DISABLED禁用，DRAFT草稿，REVIEWING审核中，REJECTED审核拒绝）',
  `level` int NOT NULL DEFAULT 1 COMMENT '标签层级（1-3）',
  `parent_tag_id` bigint unsigned DEFAULT NULL COMMENT '父标签ID',
  `parent_tag_path` varchar(512) DEFAULT NULL COMMENT '父标签路径（/1/2/3）',
  `color` varchar(16) DEFAULT NULL COMMENT '标签颜色',
  `icon` varchar(128) DEFAULT NULL COMMENT '标签图标',
  `sort_order` int DEFAULT 0 COMMENT '排序权重',
  `usage_count` bigint DEFAULT 0 COMMENT '使用计数',
  `hot_score` decimal(10,4) DEFAULT 0.0000 COMMENT '热度分数',
  `creator_id` bigint unsigned DEFAULT NULL COMMENT '创建者ID',
  `ext_attributes` text COMMENT '扩展属性（JSON格式）',
  `deleted` int DEFAULT 0 COMMENT '是否逻辑删除，0为未删除，非0为已删除',
  `lock_version` int DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_name_level_parent` (`tag_name`, `level`, `parent_tag_id`, `deleted`),
  KEY `idx_tag_type` (`tag_type`),
  KEY `idx_status` (`status`),
  KEY `idx_level` (`level`),
  KEY `idx_parent_tag_id` (`parent_tag_id`),
  KEY `idx_creator_id` (`creator_id`),
  KEY `idx_usage_count` (`usage_count`),
  KEY `idx_hot_score` (`hot_score`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签主表'
; 