spring:
  data:
    redis:
      host: ${collide.turbo.redis.url}
      port: ${collide.turbo.redis.port}
      password: ${collide.turbo.redis.password}
      database: ${collide.turbo.redis.database}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 5
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: 123456
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://172.20.1.40:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: ${collide.turbo.redis.database}
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000