package com.gig.collide.api.tag.response.data;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * 内容标签信息传输对象
 *
 * @author Collide Team
 * @version 2.0
 * @since 2024-01-01
 */
@Getter
@Setter
@ToString
@NoArgsConstructor
public class ContentTagInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 关系ID
     */
    private Long id;

    /**
     * 内容ID
     */
    private Long contentId;

    /**
     * 内容标题
     */
    private String contentTitle;

    /**
     * 内容类型
     */
    private String contentType;

    /**
     * 标签ID
     */
    private Long tagId;

    /**
     * 标签名称
     */
    private String tagName;

    /**
     * 标签颜色
     */
    private String tagColor;

    /**
     * 标签类型
     */
    private String tagType;

    /**
     * 标签图标URL
     */
    private String tagIconUrl;

    /**
     * 关联时间
     */
    private LocalDateTime createTime;

    /**
     * 版本号
     */
    private Integer version;

    /**
     * 标签权重（在内容中的重要程度）
     */
    private Integer weight;

    /**
     * 是否为主要标签
     */
    private Boolean isPrimary;

    /**
     * 自动生成标识
     */
    private Boolean isAutoGenerated;
} 