

# 数据源配置
spring:
  autoconfigure:
    exclude: org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration
  datasource:
    # 主数据源配置
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${collide.turbo.mysql.host}:${collide.turbo.mysql.port}/${collide.turbo.mysql.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true&useServerPrepStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false
      username: ${collide.turbo.mysql.username}
      password: ${collide.turbo.mysql.password}
      
      # HikariCP 连接池配置 - 优化性能
      hikari:
        # 连接池名称
        pool-name: HikariCP-Primary
        # 最小空闲连接数
        minimum-idle: 10
        # 最大连接池大小 - 增加连接数
        maximum-pool-size: 50
        # 连接超时时间（毫秒）
        connection-timeout: 30000
        # 空闲连接超时时间（毫秒）
        idle-timeout: 600000
        # 连接最大生存时间（毫秒）
        max-lifetime: 1800000
        # 连接测试查询
        connection-test-query: SELECT 1
        # 连接验证超时时间（毫秒）
        validation-timeout: 5000
        # 是否自动提交
        auto-commit: true
        # 连接初始化SQL
        connection-init-sql: SET NAMES utf8mb4
        # 连接池监控
        register-mbeans: true
        # 连接池统计
        allow-pool-suspension: false
        # 连接池泄漏检测
        leak-detection-threshold: 60000
        
    # 从数据源配置（读写分离）
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${collide.turbo.mysql.slave.host}:${collide.turbo.mysql.slave.port}/${collide.turbo.mysql.slave.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: ${collide.turbo.mysql.slave.username}
      password: ${collide.turbo.mysql.slave.password}
      
      # HikariCP 连接池配置
      hikari:
        pool-name: HikariCP-Secondary
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        validation-timeout: 5000
        auto-commit: true
        connection-init-sql: SET NAMES utf8mb4
        register-mbeans: true
        allow-pool-suspension: false
        leak-detection-threshold: 60000

# MyBatis Plus 配置
mybatis-plus:
  # 全局配置
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 乐观锁配置
      version-field: version
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
    # 性能优化配置
    banner: false
    enable-sql-runner: false
    
  # 配置项
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 延迟加载
    lazy-loading-enabled: true
    # 积极延迟加载
    aggressive-lazy-loading: false
    # 多结果集处理
    multiple-result-sets-enabled: true
    # 列标签
    use-column-label: true
    # 使用生成的主键
    use-generated-keys: true
    # 自动映射行为
    auto-mapping-behavior: partial
    # 自动映射未知列
    auto-mapping-unknown-column-behavior: warning
    # 默认执行器类型
    default-executor-type: simple
    # 默认语句超时时间
    default-statement-timeout: 10  # 减少超时时间
    # 默认获取结果集超时时间
    default-fetch-size: 50         # 减少批量大小
    # 安全行边界
    safe-row-bounds-enabled: false
    # 安全结果处理
    safe-result-handler-enabled: true
    # 本地缓存作用域
    local-cache-scope: session
    # 设置但空字符串列的值
    call-setters-on-nulls: false
    # 指定VARCHAR的返回类型
    return-instance-for-empty-row: false
    # 日志前缀
    log-prefix: MyBatis
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
  # 类型别名包扫描
  type-aliases-package: com.gig.collide.*.domain.entity
  # Mapper XML 文件位置
  mapper-locations: classpath*:mapper/*.xml

# 数据库连接池监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hikaricp
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 自定义数据源配置
collide:
  datasource:
    # 连接池监控
    monitoring:
      enabled: true
      # 慢查询阈值（毫秒）
      slow-query-threshold: 1000
      # 连接池监控间隔（秒）
      monitor-interval: 30
    # 性能优化
    performance:
      # 启用查询缓存
      query-cache-enabled: true
      # 启用二级缓存
      second-level-cache-enabled: true
      # 批量操作大小
      batch-size: 1000
      # 分页查询优化
      page-query-optimization: true



