# Collide Gateway 多环境配置
spring:
  application:
    name: @application.name@
  config:
    import:
      - classpath:base.yml
      - classpath:cache.yml
      - classpath:config.yml
      - classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/api/v1/auth/**,/api/v1/token/**

        # 业务服务路由 - 完整模块覆盖
        - id: collide-application
          uri: lb://collide-application
          predicates:
            - Path=/api/v1/users/**,/api/v1/follow/**,/api/v1/comments/**,/api/v1/content/**,/api/v1/social/**,/api/v1/favorite/**,/api/v1/like/**,/api/v1/files/**,/api/v1/search/**,/api/v1/categories/**,/api/v1/tags/**

        # API文档导航页面
        - id: api-docs-home
          uri: lb://collide-application
          predicates:
            - Path=/swagger-ui.html,/docs,/api-docs
          filters:
            - SetPath=/swagger-ui.html

        # Swagger UI 路由 - 认证服务
        - id: collide-auth-swagger
          uri: lb://collide-auth
          predicates:
            - Path=/auth/swagger-ui/**,/auth/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Swagger UI 路由 - 业务服务
        - id: collide-application-swagger
          uri: lb://collide-application
          predicates:
            - Path=/app/swagger-ui/**,/app/v3/api-docs/**
          filters:
            - StripPrefix=1

        # 网关本身的监控端点
        - id: gateway-actuator
          uri: lb://collide-gateway
          predicates:
            - Path=/actuator/**

server:
  port: 9501