# Collide Gateway 多环境配置
spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        # =================== 核心服务路由 ===================
        
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/api/v1/auth/**,/api/v1/token/**

        # =================== FastAPI业务服务路由 ===================

        - id: collide-api-service
          uri: lb://collide-api-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/content/**, /api/v1/categories/**, /api/v1/social/**, /api/v1/comments/**, /api/v1/likes/**, /api/v1/ads/**, /api/v1/favorites/**, /api/v1/follows/**, /api/v1/goods/**, /api/v1/messages/**, /api/v1/search/**, /api/v1/tags/**, /api/v1/tasks/**
          filters:
            - name: SaTokenUserInfo


        # 健康检查路由
        - id: collide-api-service-health
          uri: lb://collide-api-service
          predicates:
            - Path=/health,/actuator/health

        # API文档路由
        - id: collide-api-service-docs
          uri: lb://collide-api-service
          predicates:
            - Path=/docs,/docs/**,/redoc,/redoc/**,/openapi.json

server:
  port: 9501