# Collide Gateway 多环境配置
spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        # =================== 核心服务路由 ===================
        
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/api/v1/auth/**,/api/v1/token/**

        # =================== 业务服务路由 ===================
        
        # 用户服务路由
        - id: collide-users
          uri: lb://collide-users
          predicates:
            - Path=/api/v1/users/**
            
        # 内容服务路由
        - id: collide-content
          uri: lb://collide-content
          predicates:
            - Path=/api/v1/content/**
            
        # 分类服务路由
        - id: collide-category
          uri: lb://collide-category
          predicates:
            - Path=/api/v1/categories/**
            
        # 评论服务路由
        - id: collide-comment
          uri: lb://collide-comment
          predicates:
            - Path=/api/v1/comments/**
            
        # 社交服务路由
        - id: collide-social
          uri: lb://collide-social
          predicates:
            - Path=/api/v1/social/**
            
        # 标签服务路由
        - id: collide-tag
          uri: lb://collide-tag
          predicates:
            - Path=/api/v1/tags/**
            
        # 标签服务兼容路由（支持文档中的/api/tags路径）
        - id: collide-tag-compat
          uri: lb://collide-tag
          predicates:
            - Path=/api/tags/**
          filters:
            - RewritePath=/api/tags/(?<segment>.*), /api/v1/tags/$\{segment}

        # =================== 交互服务路由 ===================
        
        # 点赞服务路由
        - id: collide-like
          uri: lb://collide-like
          predicates:
            - Path=/api/v1/like/**
            
        # 收藏服务路由
        - id: collide-favorite
          uri: lb://collide-favorite
          predicates:
            - Path=/api/v1/favorite/**
            
        # 关注服务路由
        - id: collide-follow
          uri: lb://collide-follow
          predicates:
            - Path=/api/v1/follow/**

        # =================== 电商服务路由 ===================
        
        # 商品服务路由
        - id: collide-goods
          uri: lb://collide-goods
          predicates:
            - Path=/api/v1/goods/**
            
        # 订单服务路由
        - id: collide-order
          uri: lb://collide-order
          predicates:
            - Path=/api/v1/orders/**
            
        # 支付服务路由
        - id: collide-payment
          uri: lb://collide-payment
          predicates:
            - Path=/api/v1/payments/**

        # =================== 工具服务路由 ===================
        
        # 搜索服务路由
        - id: collide-search
          uri: lb://collide-search
          predicates:
            - Path=/api/v1/search/**
            
        # 文件服务路由 (如果有独立文件服务)
        - id: collide-files
          uri: lb://collide-files
          predicates:
            - Path=/api/v1/files/**

server:
  port: 9501