# 网关服务 Docker环境配置
server:
  port: ${SERVER_PORT:9500}

spring:
  application:
    name: collide-gateway
  
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_SERVER_USERNAME:nacos}
        password: ${NACOS_SERVER_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        cluster-name: ${NACOS_CLUSTER:docker}
        metadata:
          version: ${APP_VERSION:1.0.0}
          environment: ${APP_ENVIRONMENT:docker}
    
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: ${CORS_MAX_AGE:3600}
      routes:
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/auth/**
        # 业务服务路由
        - id: collide-application
          uri: lb://collide-business
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: ${GATEWAY_DISCOVERY_ENABLED:true}
          lower-case-service-id: ${GATEWAY_LOWER_CASE_SERVICE:true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:6000}ms
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:20}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1}ms
          max-idle: ${REDIS_POOL_MAX_IDLE:10}
          min-idle: ${REDIS_POOL_MIN_IDLE:0}

# Sa-Token 配置
sa-token:
  jwt-secret-key: ${SA_TOKEN_SECRET:CollideGatewaySecretKey2024}
  token-name: ${SA_TOKEN_NAME:satoken}
  timeout: ${SA_TOKEN_TIMEOUT:2592000}
  active-timeout: ${SA_TOKEN_ACTIVE_TIMEOUT:-1}
  is-concurrent: ${SA_TOKEN_CONCURRENT:true}
  is-share: ${SA_TOKEN_SHARE:true}
  token-style: ${SA_TOKEN_STYLE:uuid}
  is-log: ${SA_TOKEN_LOG:true}

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.gig.collide: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:DEBUG}
  file:
    name: ${LOG_FILE_PATH:/app/logs/gateway.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,gateway}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always} 