spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:config.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/api/v1/auth/**, ,/api/v1/token/**
            -
        # 业务服务路由
        - id: collide-application
          uri: lb://collide-business
          predicates:
            - Path=/api/v1/users/**,/api/v1/follow/**,/api/v1/comments/**,/api/v1/content/**

      # 全局过滤器配置
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9501