# Collide Gateway 多环境配置
spring:
  application:
    name: @application.name@
  config:
    import:
      - classpath:base.yml
      - classpath:cache.yml
      - classpath:config.yml
      - classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        # 认证服务路由
        - id: collide-auth
          uri: lb://collide-auth
          predicates:
            - Path=/api/v1/auth/**,/api/v1/token/**

        # 业务服务路由
        - id: collide-application
          uri: lb://collide-application
          predicates:
            - Path=/api/v1/users/**,/api/v1/follow/**,/api/v1/comments/**,/api/v1/content/**

server:
  port: 9501