# Collide Auth 多环境配置
spring:
  application:
    name: collide-auth
  config:
    import: classpath:base.yml,classpath:config.yml,classpath:rpc.yml,classpath:cache.yml,classpath:datasource.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: ${SA_TOKEN_NAME:satoken}
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: ${SA_TOKEN_TIMEOUT:2592000}
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: ${SA_TOKEN_ACTIVE_TIMEOUT:-1}
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: ${SA_TOKEN_IS_CONCURRENT:true}
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: ${SA_TOKEN_IS_SHARE:true}
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: ${SA_TOKEN_STYLE:uuid}
  # 是否输出操作日志
  is-log: ${SA_TOKEN_IS_LOG:true}

# 默认配置（开发环境）
server:
  port: ${SERVER_PORT:9502}
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    root: INFO
    com.gig.collide: DEBUG
    cn.dev33.satoken: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger] - %msg%n"
  file:
    name: logs/collide-auth.log

# Swagger文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  info:
    title: Collide Auth API
    description: Collide社交平台认证授权服务API文档
    version: 1.0.0

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev

sa-token:
  timeout: 7200        # 开发环境token 2小时过期
  active-timeout: 3600  # 开发环境1小时不活跃过期
  is-log: true

server:
  port: 9502

logging:
  level:
    com.gig.collide: DEBUG
    cn.dev33.satoken: DEBUG

springdoc:
  swagger-ui:
    enabled: true  # 开发环境启用Swagger

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test

sa-token:
  timeout: 86400       # 测试环境token 1天过期
  active-timeout: 7200  # 测试环境2小时不活跃过期
  is-concurrent: false  # 测试环境不允许多地登录
  is-log: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.gig.collide: INFO
    cn.dev33.satoken: INFO

springdoc:
  swagger-ui:
    enabled: true  # 测试环境启用Swagger

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

sa-token:
  timeout: 2592000     # 生产环境token 30天过期
  active-timeout: 86400 # 生产环境1天不活跃过期
  is-concurrent: false  # 生产环境不允许多地登录
  is-share: false      # 生产环境每次登录新建token
  is-log: false        # 生产环境关闭详细日志

server:
  port: 8081

logging:
  level:
    root: WARN
    com.gig.collide: INFO
    cn.dev33.satoken: WARN
  file:
    name: /var/log/collide/auth.log

springdoc:
  swagger-ui:
    enabled: false  # 生产环境禁用Swagger
