# 认证服务 Docker环境配置
server:
  port: ${SERVER_PORT:9501}

spring:
  application:
    name: collide-auth
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:collide_db}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=${DB_TIMEZONE:Asia/Shanghai}&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:collide}
    password: ${MYSQL_PASSWORD:collide123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: CollideAuthHikariCP
      minimum-idle: ${DB_POOL_MIN:5}
      maximum-pool-size: ${DB_POOL_MAX:15}
      connection-timeout: ${DB_CONN_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:6000}ms
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:15}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1}ms
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:0}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_SERVER_USERNAME:nacos}
        password: ${NACOS_SERVER_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        cluster-name: ${NACOS_CLUSTER:docker}
        metadata:
          version: ${APP_VERSION:1.0.0}
          environment: ${APP_ENVIRONMENT:docker}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_SERVER_USERNAME:nacos}
        password: ${NACOS_SERVER_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${NACOS_SERVER_ADDR:localhost:8848}
    username: ${NACOS_SERVER_USERNAME:nacos}
    password: ${NACOS_SERVER_PASSWORD:nacos}
    parameters:
      namespace: ${NACOS_NAMESPACE:}
  protocol:
    name: dubbo
    port: ${DUBBO_PORT:20881}
    host: ${DUBBO_HOST:}
  provider:
    timeout: ${DUBBO_TIMEOUT:10000}
    retries: ${DUBBO_RETRIES:0}

# Sa-Token 配置
sa-token:
  token-name: ${SA_TOKEN_NAME:satoken}
  timeout: ${SA_TOKEN_TIMEOUT:2592000}
  active-timeout: ${SA_TOKEN_ACTIVE_TIMEOUT:-1}
  is-concurrent: ${SA_TOKEN_CONCURRENT:true}
  is-share: ${SA_TOKEN_SHARE:true}
  token-style: ${SA_TOKEN_STYLE:uuid}
  is-log: ${SA_TOKEN_LOG:true}
  jwt-secret-key: ${SA_TOKEN_SECRET:CollideAuthSecretKey2024}

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.gig.collide: ${LOG_LEVEL_APP:DEBUG}
    org.apache.dubbo: ${LOG_LEVEL_DUBBO:INFO}
  file:
    name: ${LOG_FILE_PATH:/app/logs/auth.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always} 