spring:
  profiles:
    active: dev
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:config.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:prometheus.yml

# 服务器配置
server:
  port: 9503

dubbo:
  application:
    qos-port: 33334