# Collide Business 多环境配置
spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:config.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:prometheus.yml,classpath:swagger.yml

server:
  port: 9503

dubbo:
  application:
    qos-port: 33334