# 业务应用服务 Docker环境配置
server:
  port: ${SERVER_PORT:9502}

spring:
  application:
    name: collide-business
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:collide_db}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=${DB_TIMEZONE:Asia/Shanghai}&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: CollideBusinessHikariCP
      minimum-idle: ${DB_POOL_MIN:10}
      maximum-pool-size: ${DB_POOL_MAX:50}
      connection-timeout: ${DB_CONN_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}  
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:6000}ms
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:30}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1}ms
          max-idle: ${REDIS_POOL_MAX_IDLE:15}
          min-idle: ${REDIS_POOL_MIN_IDLE:5}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_SERVER_USERNAME:nacos}
        password: ${NACOS_SERVER_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        cluster-name: ${NACOS_CLUSTER:docker}
        metadata:
          version: ${APP_VERSION:1.0.0}
          environment: ${APP_ENVIRONMENT:docker}

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${NACOS_SERVER_ADDR:localhost:8848}
    username: ${NACOS_SERVER_USERNAME:nacos}
    password: ${NACOS_SERVER_PASSWORD:nacos}
    parameters:
      namespace: ${NACOS_NAMESPACE:}
  protocols:
    dubbo:
      name: dubbo
      port: ${DUBBO_PORT:20882}
      host: ${DUBBO_HOST:}
  provider:
    timeout: ${DUBBO_TIMEOUT:10000}
    retries: ${DUBBO_RETRIES:0}
    loadbalance: ${DUBBO_LOADBALANCE:roundrobin}

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.*.domain.entity
  configuration:
    map-underscore-to-camel-case: ${MYBATIS_CAMEL_CASE:true}
    cache-enabled: ${MYBATIS_CACHE:false}
    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
  global-config:
    db-config:
      id-type: ${MYBATIS_ID_TYPE:auto}
      logic-delete-field: ${MYBATIS_LOGIC_DELETE_FIELD:deleted}
      logic-delete-value: ${MYBATIS_LOGIC_DELETE_VALUE:1}
      logic-not-delete-value: ${MYBATIS_LOGIC_NOT_DELETE_VALUE:0}

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.gig.collide: ${LOG_LEVEL_APP:DEBUG}
    org.apache.dubbo: ${LOG_LEVEL_DUBBO:INFO}
    com.baomidou.mybatisplus: ${LOG_LEVEL_MYBATIS:DEBUG}
  file:
    name: ${LOG_FILE_PATH:/app/logs/business.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,dubbo}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
    dubbo:
      enabled: ${MANAGEMENT_DUBBO_ENABLED:true} 