# =====================================
# Collide Business 聚合应用配置
# 参考 nft-turbo-app 的配置管理架构
# =====================================
spring:
  application:
    name: @application.name@
  config:
    # 参考 nft-turbo-app 的多配置文件导入方式
    import: classpath:base.yml,classpath:config.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:prometheus.yml
  # 参考 nft-turbo-app 的主配置懒加载优化
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true


server:
  port: 9503


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 33334
    qos-enable: true
  registry:
    address: nacos://localhost:8848
    group: DEFAULT_GROUP
    timeout: 3000
  protocol:
    name: dubbo
    port: -1
    threads: 200
  consumer:
    timeout: 3000
    retries: 0
    check: false
  provider:
    timeout: 3000
    threads: 200

logging:
  level:
    com.gig.collide: info
    org.apache.dubbo: warn
    com.alibaba.nacos: warn
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"