spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9611

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.search.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 搜索模块专用配置
collide:
  search:
    # 搜索历史保留天数
    history-retention-days: 90
    # 热搜关键词最大数量
    hot-keywords-max-size: 50
    # 搜索建议最大数量
    suggestions-max-size: 10
    # 趋势分数计算间隔（小时）
    trend-score-interval: 1
    # 无结果搜索记录开关
    log-no-results: true
    # 搜索防刷限制（每分钟）
    rate-limit-per-minute: 60 