-- 内容主表
CREATE TABLE `content` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '内容ID',
    `content_type` varchar(50) NOT NULL COMMENT '内容类型：novel-小说，comic-漫画，short_video-短视频，long_video-长视频',
    `title` varchar(200) NOT NULL COMMENT '内容标题',
    `description` text COMMENT '内容描述',
    `cover_image` varchar(500) COMMENT '内容封面图URL',
    `content_url` varchar(1000) NOT NULL COMMENT '内容URL（视频地址、小说章节地址等）',
    `duration` int(11) COMMENT '内容时长（视频专用，单位：秒）',
    `file_size` bigint(20) COMMENT '内容大小（字节）',
    `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '内容状态：1-草稿，2-待审核，3-已发布，4-审核拒绝，5-已下架，6-已删除',
    `creator_user_id` bigint(20) NOT NULL COMMENT '创建者用户ID',
    `creator_username` varchar(100) COMMENT '创建者用户名',
    `tags` json COMMENT '标签列表（JSON数组）',
    `category` varchar(100) COMMENT '分类',
    `is_original` tinyint(1) DEFAULT '1' COMMENT '是否原创：0-否，1-是',
    `age_rating` varchar(20) COMMENT '年龄分级',
    `language` varchar(20) DEFAULT 'zh' COMMENT '语言',
    `view_count` bigint(20) DEFAULT '0' COMMENT '查看次数',
    `like_count` bigint(20) DEFAULT '0' COMMENT '点赞次数',
    `collect_count` bigint(20) DEFAULT '0' COMMENT '收藏次数',
    `share_count` bigint(20) DEFAULT '0' COMMENT '分享次数',
    `comment_count` bigint(20) DEFAULT '0' COMMENT '评论次数',
    `download_count` bigint(20) DEFAULT '0' COMMENT '下载次数',
    `rating` decimal(3,2) DEFAULT '0.00' COMMENT '评分（0-5分）',
    `rating_count` bigint(20) DEFAULT '0' COMMENT '评分人数',
    `hot_score` decimal(10,2) DEFAULT '0.00' COMMENT '热度分数',
    `quality_score` decimal(10,2) DEFAULT '0.00' COMMENT '质量分数',
    `recommend_index` decimal(10,2) DEFAULT '0.00' COMMENT '推荐指数',
    `publish_time` datetime COMMENT '发布时间',
    `extend_info` json COMMENT '扩展信息（JSON格式，用于存储各类型特有的属性）',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_content_type` (`content_type`),
    KEY `idx_status` (`status`),
    KEY `idx_creator_user_id` (`creator_user_id`),
    KEY `idx_category` (`category`),
    KEY `idx_publish_time` (`publish_time`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_hot_score` (`hot_score`),
    KEY `idx_view_count` (`view_count`),
    KEY `idx_like_count` (`like_count`),
    KEY `idx_rating` (`rating`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容主表'; 