-- 内容审核表
CREATE TABLE `content_review` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '审核ID',
    `content_id` bigint(20) NOT NULL COMMENT '内容ID',
    `review_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '审核状态：1-待审核，2-审核中，3-审核通过，4-审核拒绝，5-需要重审',
    `reviewer_user_id` bigint(20) COMMENT '审核员用户ID',
    `reviewer_username` varchar(100) COMMENT '审核员用户名',
    `review_comment` varchar(500) COMMENT '审核意见',
    `review_reason` varchar(200) COMMENT '审核原因',
    `violation_type` varchar(100) COMMENT '违规类型',
    `review_round` int(11) NOT NULL DEFAULT '1' COMMENT '审核轮次',
    `need_manual_review` tinyint(1) DEFAULT '0' COMMENT '是否需要人工审核：0-否，1-是',
    `ai_review_result` text COMMENT '机器审核结果',
    `ai_confidence` decimal(5,4) COMMENT '机器审核置信度（0-1）',
    `priority` int(11) DEFAULT '0' COMMENT '优先级（数字越大优先级越高）',
    `submit_time` datetime COMMENT '提交审核时间',
    `start_time` datetime COMMENT '开始审核时间',
    `finish_time` datetime COMMENT '完成审核时间',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_content_id` (`content_id`),
    KEY `idx_review_status` (`review_status`),
    KEY `idx_reviewer_user_id` (`reviewer_user_id`),
    KEY `idx_review_round` (`review_round`),
    KEY `idx_priority` (`priority`),
    KEY `idx_submit_time` (`submit_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容审核表'; 