-- 内容统计表
CREATE TABLE `content_statistics` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '统计ID',
    `content_id` bigint(20) NOT NULL COMMENT '内容ID',
    `statistics_date` varchar(10) NOT NULL COMMENT '统计日期（YYYY-MM-DD）',
    `view_count` bigint(20) DEFAULT '0' COMMENT '查看次数',
    `today_view_count` bigint(20) DEFAULT '0' COMMENT '今日查看次数',
    `like_count` bigint(20) DEFAULT '0' COMMENT '点赞次数',
    `today_like_count` bigint(20) DEFAULT '0' COMMENT '今日点赞次数',
    `collect_count` bigint(20) DEFAULT '0' COMMENT '收藏次数',
    `today_collect_count` bigint(20) DEFAULT '0' COMMENT '今日收藏次数',
    `share_count` bigint(20) DEFAULT '0' COMMENT '分享次数',
    `today_share_count` bigint(20) DEFAULT '0' COMMENT '今日分享次数',
    `comment_count` bigint(20) DEFAULT '0' COMMENT '评论次数',
    `today_comment_count` bigint(20) DEFAULT '0' COMMENT '今日评论次数',
    `download_count` bigint(20) DEFAULT '0' COMMENT '下载次数',
    `today_download_count` bigint(20) DEFAULT '0' COMMENT '今日下载次数',
    `play_completion_rate` decimal(5,4) COMMENT '播放完成率（视频专用）',
    `avg_watch_duration` int(11) COMMENT '平均观看时长（视频专用，单位：秒）',
    `bounce_rate` decimal(5,4) COMMENT '跳出率',
    `retention_rate` decimal(5,4) COMMENT '用户留存率',
    `revenue` bigint(20) DEFAULT '0' COMMENT '收入（分）',
    `today_revenue` bigint(20) DEFAULT '0' COMMENT '今日收入（分）',
    `hot_score` decimal(10,2) DEFAULT '0.00' COMMENT '热度分数',
    `quality_score` decimal(10,2) DEFAULT '0.00' COMMENT '质量分数',
    `recommend_index` decimal(10,2) DEFAULT '0.00' COMMENT '推荐指数',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_date` (`content_id`, `statistics_date`),
    KEY `idx_content_id` (`content_id`),
    KEY `idx_statistics_date` (`statistics_date`),
    KEY `idx_hot_score` (`hot_score`),
    KEY `idx_quality_score` (`quality_score`),
    KEY `idx_view_count` (`view_count`),
    KEY `idx_like_count` (`like_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容统计表'; 