# SpringDoc OpenAPI 配置
springdoc:
  # API文档配置
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  
  # Swagger UI配置
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: default
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    display-operation-id: false
    show-extensions: false
    show-common-extensions: false
    use-root-path: false
    disable-swagger-default-url: true
    
  # OpenAPI配置
  override-with-generic-response: false
  cache:
    disabled: false
  
  # 路径匹配配置 - 包含所有API路径
  paths-to-match: 
    - /api/**
    - /health/**
    - /actuator/**
  
  # 包扫描配置 - 包含所有控制器包
  packages-to-scan: 
    - com.gig.collide.users.controller
    - com.gig.collide.follow.controller
    - com.gig.collide.content.controller
    - com.gig.collide.comment.controller
    - com.gig.collide.like.controller
    - com.gig.collide.favorite.controller
    - com.gig.collide.social.controller
    - com.gig.collide.business.controller
    - com.gig.collide.business.infrastructure.controller
    - com.gig.collide.auth.controller
  
  # 默认响应配置
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  
  # 预处理器配置
  pre-loading-enabled: true
  
  # 写入超时
  writer-with-default-pretty-printer: true

# 静态资源配置
spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
      add-mappings: true
  mvc:
    static-path-pattern: /**
  
# 管理端点配置（用于健康检查和监控）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  info:
    env:
      enabled: true 