# 这是项目的需要改动的所有配置的地址的汇总，需要改哪个中间件的地址，在本文件中修改即可！
collide:
  turbo:
    nacos:
      server:
        url: 192.168.1.107:8848
        username: nacos
        password: nacos
    mysql:
      url: jdbc:mysql://192.168.1.107:3306/collide
      username: root
      password: '123456'
    redis:
      url: redis://192.168.1.107
      port: 6379
      password: '123456'
    elasticsearch:
      enable: false
      url: 192.168.1.107:5601
      username: elastic
      password: 123456
    xxl-job:
      url: 192.168.1.107:8081
      appName: xxl-job-executor
      accessToken: default_token
    sentinel:
      url: 192.168.1.107
      port: 8888
      nacos:
        data-id: collide-gateway-sentinel
    rocketmq:
      url: 192.168.1.107:9876
    dubbo:
      nacos:
        namespace: b8bca988-2d8a-4d2b-a9a0-c26127e345bc
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.properties
        group: seata
        namespace: 806e806f-e916-411c-b4ba-9682ae44b47e