collide:
  turbo:
    nacos:
      server:
        url: 192.168.1.107:8848
        username: nacos
        password: nacos
        # 增加超时配置
        connect-timeout: 30000        # 连接超时30秒
        server-check-timeout: 30000   # 服务器检查超时30秒
        config-retry-time: 5000       # 配置重试间隔5秒
        config-long-poll-timeout: 60000 # 长轮询超时60秒

    mysql:
      url: jdbc:mysql://192.168.1.107:3306/collide
      username: root
      password: '123456'
    redis:
      url: 192.168.1.107
      port: 6379
      password: 123456
      database: 0
    elasticsearch:
      enable: false
      url: 192.168.1.107:9200
      username: elastic
      password: 123456
    sentinel:
      url: 192.168.1.107
      port: 8888
      nacos:
        data-id: ${spring.application.name}-sentinel
    rocketmq:
      url: 192.168.1.107:9876
    dubbo:
      nacos:
        namespace: 5d02cdf0-69f6-40a9-aca8-2006ac430045
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.Properties
        group: seata-server
        namespace: 806e806f-e916-411c-b4ba-9682ae44b47e