# Collide项目多环境基础配置
# 默认配置（开发环境）
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      file-size-threshold: 2KB

collide:
  turbo:
    nacos:
      server:
        url: 18.166.150.123:8848
        username: nacos
        password: nacos
      grpc: 10848

    mysql:
      url: 18.166.150.123
      port: 3306
      database: collide
      username: root
      password: 123456
    redis:
      url: 18.166.150.123
      port: 6379
      password: 123456
      database: 0
    elasticsearch:
      enable: false
      url: 18.166.150.123:9200
      username: elastic
      password: 123456
    xxl-job:
      url: 18.166.150.123:8081
      appName: ${spring.application.name}-executor
      accessToken: ${XXL_JOB_ACCESS_TOKEN:default_token}
    sentinel:
      url: 18.166.150.123
      port: 8888
      nacos:
        data-id: ${spring.application.name}-sentinel
    rocketmq:
      url: 18.166.150.123:9876
    dubbo:
      nacos:
        namespace: 3537371b-bdbf-4989-a17e-6b173101c18a
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.Properties
        group: seata
        namespace: 7ebdfb9b-cd9d-4a5e-8969-1ada0bb9ba04