# 开发环境配置 - 使用已部署的中间件
spring:
  servlet:
    multipart:
      max-file-size: 100MB        # 单个文件最大大小
      max-request-size: 200MB     # 请求最大大小(多文件上传时)
      file-size-threshold: 2KB    # 写入磁盘的阈值

collide:
  turbo:
    nacos:
      server:
        url: localhost:8848   # 使用已部署的 Nacos
        username: nacos
        password: nacos
    mysql:
      url: jdbc:mysql://localhost:3306/collide  # 使用已部署的 MySQL
      username: root
      password: '123456'
    redis:
      url: redis://localhost  # 使用已部署的 Redis
      port: 6379
      password: '123456'
    elasticsearch:
      enable: true
      url: localhost:9200     # 使用已部署的 ES
      username: elastic
      password: 123456
    xxl-job:
      url: localhost:8081     # 使用已部署的 XXL-Job
      appName: xxl-job-executor
      accessToken: default_token
    sentinel:
      url: localhost         # 使用已部署的 Sentinel
      port: 8888
      nacos:
        data-id: collide-gateway-sentinel
    rocketmq:
      url: localhost:9876     # 使用已部署的 RocketMQ
    dubbo:
      nacos:
        namespace: 99d4c548-be12-4eaa-9564-4c7921bd80c1  # 使用生产环境的 namespace
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.properties
        group: seata
        namespace: 806e806f-e916-411c-b4ba-9682ae44b47e  # 使用生产环境的 namespace 