# Collide项目多环境基础配置
# 默认配置（开发环境）
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      file-size-threshold: 2KB

collide:
  turbo:
    nacos:
      server:
        url: 192.168.1.107:8848
        username: nacos
        password: nacos
        # 增加超时配置
        connect-timeout: 30000        # 连接超时30秒
        server-check-timeout: 30000   # 服务器检查超时30秒
        config-retry-time: 5000       # 配置重试间隔5秒
        config-long-poll-timeout: 60000 # 长轮询超时60秒

    mysql:
      url: jdbc:mysql://192.168.1.107:3306/collide
      username: root
      password: '123456'
    redis:
      url: 192.168.1.107
      port: 6379
      password: 123456
      database: 0
    elasticsearch:
      enable: false
      url: 192.168.1.107:9200
      username: elastic
      password: 123456
    xxl-job:
      url: 192.168.1.107:8081
      appName: ${spring.application.name}-executor
      accessToken: ${XXL_JOB_ACCESS_TOKEN:default_token}
    sentinel:
      url: 192.168.1.107
      port: 8888
      nacos:
        data-id: ${spring.application.name}-sentinel
    rocketmq:
      url: 192.168.1.107:9876
    dubbo:
      nacos:
        namespace: b8bca988-2d8a-4d2b-a9a0-c26127e345bc
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.Properties
        group: seata
        namespace: 7ebdfb9b-cd9d-4a5e-8969-1ada0bb9ba04