# 这是项目的需要改动的所有配置的地址的汇总，需要改哪个中间件的地址，在本文件中修改即可！

spring:
  servlet:
    multipart:
      max-file-size: 100MB        # 单个文件最大大小
      max-request-size: 200MB     # 请求最大大小(多文件上传时)
      file-size-threshold: 2KB    # 写入磁盘的阈值

collide:
  turbo:
    nacos:
      server:
        url: localhost:8848
        username: nacos
        password: nacos
    mysql:
      url: jdbc:mysql://localhost:3306/collide
      username: root
      password: '123456'
    redis:
      url: redis://localhost
      port: 6379
      password: '123456'
    elasticsearch:
      enable: true
      url: localhost:9200
      username: elastic
      password: 123456
    xxl-job:
      url: localhost:8081
      appName: xxl-job-executor
      accessToken: default_token
    sentinel:
      url: localhost
      port: 8888
      nacos:
        data-id: collide-gateway-sentinel
    rocketmq:
      url: localhost:9876
    dubbo:
      nacos:
        namespace: 99d4c548-be12-4eaa-9564-4c7921bd80c1
        group: dubbo
    seata:
      nacos:
        data-id: seataServer.properties
        group: seata
        namespace: 806e806f-e916-411c-b4ba-9682ae44b47e