spring:
  xxl:
    job:
      enabled: false
  autoconfigure:
    exclude: org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration
  elasticsearch:
    enable: true
  easy-es:
    enable: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  datasource:
    url: jdbc:h2:mem:nfturbo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    h2-console-setting: INIT=RUNSCRIPT FROM 'classpath:schema.sql'


# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: nft-turbo-business
  registry:
    address: nacos://192.168.1.107
  consumer:
    check: false
