# ========================================================================
# Collide Order Service - 标准化配置
# 订单服务配置，采用标准化组件配置，简化维护成本
# ========================================================================

spring:
  profiles:
    active: dev
  application:
    name: collide-order

# 服务端口配置
server:
  port: 9503

# ========================================================================
# 标准化组件配置 - 依赖各组件的默认配置
# ========================================================================

# 数据源配置 - 由 collide-datasource 组件提供
# 缓存配置 - 由 collide-cache 组件提供  
# RPC配置 - 由 collide-rpc 组件提供
# 消息队列配置 - 由 collide-mq 组件提供
# 分布式锁配置 - 由 collide-lock 组件提供

# ========================================================================
# 订单业务配置
# ========================================================================
collide:
  order:
    # 订单过期时间（分钟）
    expire-minutes: 30
    # 支付超时时间（分钟）  
    pay-timeout-minutes: 15
    # 批量处理最大数量
    batch-max-size: 100
    # 幂等性缓存过期时间（小时）
    idempotency-cache-hours: 24

# ========================================================================
# MyBatis-Plus 配置 - 对齐Code项目标准化思想
# ========================================================================
mybatis-plus:
  # Mapper XML文件路径（使用标准化命名：*_sqlmap.xml）
  mapper-locations: classpath:mapper/*_sqlmap.xml
  # 类型别名包路径
  type-aliases-package: com.gig.collide.order.domain.entity
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 日志实现（开发环境）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键策略
      id-type: assign_id

# ========================================================================
# 日志配置 - 标准化日志输出
# ========================================================================
logging:
  level:
    com.gig.collide.order: INFO
    org.apache.dubbo: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15t] %-5level %-40.40logger{39} : %msg%n"

# ========================================================================
# 环境配置 - 多环境配置管理
# ========================================================================

---
# 开发环境
spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    com.gig.collide.order: DEBUG
    com.gig.collide: DEBUG
    
---
# 测试环境  
spring:
  config:
    activate:
      on-profile: test
      
logging:
  level:
    com.gig.collide.order: INFO
    
---
# 生产环境
spring:
  config:
    activate:
      on-profile: prod
      
logging:
  level:
    com.gig.collide.order: WARN
    org.apache.dubbo: ERROR 