# ========================================================================
# Collide Order Service - 标准化配置
# 订单服务配置，采用标准化组件配置，简化维护成本
# ========================================================================

spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9609

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.order.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 订单模块专用配置
collide:
  order:
    # 订单号前缀
    order-no-prefix: "ORD"
    # 订单超时时间（分钟）
    timeout-minutes: 30
    # 自动取消超时订单开关
    auto-cancel-timeout: true
    # 库存扣减策略：order（下单扣减）、pay（支付扣减）
    stock-deduct-strategy: "order"
    # 订单状态同步间隔（分钟）
    status-sync-interval: 5

logging:
  level:
    com.gig.collide.order: INFO
    org.apache.dubbo: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15t] %-5level %-40.40logger{39} : %msg%n"