-- 博主主表
CREATE TABLE `artist` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '博主ID（自增主键）',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '最后更新时间',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `artist_name` varchar(128) NOT NULL COMMENT '博主名称',
  `bio` text COMMENT '博主简介',
  `status` varchar(32) NOT NULL DEFAULT 'APPLYING' COMMENT '博主状态（APPLYING申请中，REVIEWING审核中，ACTIVE已激活，REJECTED审核拒绝，SUSPENDED已暂停，DISABLED已禁用，CANCELLED已注销）',
  `application_type` varchar(32) NOT NULL COMMENT '申请类型（PERSONAL个人，ORGANIZATION机构，BRAND品牌，MEDIA媒体，KOL，PROFESSIONAL专业）',
  `categories` text COMMENT '博主分类（JSON格式）',
  `level` varchar(32) DEFAULT 'NEWCOMER' COMMENT '博主等级（NEWCOMER新手，GROWING成长，EXCELLENT优秀，FAMOUS知名，TOP顶级）',
  `avatar_url` varchar(512) DEFAULT NULL COMMENT '头像URL',
  `cover_url` varchar(512) DEFAULT NULL COMMENT '封面图URL',
  `personal_url` varchar(512) DEFAULT NULL COMMENT '个人主页URL',
  `followers_count` int DEFAULT 0 COMMENT '粉丝数量',
  `following_count` int DEFAULT 0 COMMENT '关注数量',
  `works_count` int DEFAULT 0 COMMENT '作品数量',
  `total_likes` bigint DEFAULT 0 COMMENT '获赞总数',
  `total_views` bigint DEFAULT 0 COMMENT '总浏览量',
  `verified` tinyint(1) DEFAULT 0 COMMENT '是否认证（0否，1是）',
  `verification_type` varchar(64) DEFAULT NULL COMMENT '认证类型',
  `verification_desc` varchar(256) DEFAULT NULL COMMENT '认证说明',
  `contact_email` varchar(128) DEFAULT NULL COMMENT '联系邮箱',
  `contact_phone` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `social_media_accounts` text COMMENT '社交媒体账号（JSON格式）',
  `expertise_tags` text COMMENT '擅长领域标签（JSON格式）',
  `collaboration_intent` text COMMENT '合作意向',
  `hot_score` decimal(10,4) DEFAULT 0.0000 COMMENT '热度分数',
  `influence_index` decimal(10,4) DEFAULT 0.0000 COMMENT '影响力指数',
  `last_active_time` datetime DEFAULT NULL COMMENT '最后活跃时间',
  `ext_info` text COMMENT '扩展信息（JSON格式）',
  `deleted` int DEFAULT 0 COMMENT '是否逻辑删除，0为未删除，非0为已删除',
  `lock_version` int DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`, `deleted`),
  UNIQUE KEY `uk_artist_name` (`artist_name`, `deleted`),
  KEY `idx_status` (`status`),
  KEY `idx_application_type` (`application_type`),
  KEY `idx_level` (`level`),
  KEY `idx_verified` (`verified`),
  KEY `idx_followers_count` (`followers_count`),
  KEY `idx_hot_score` (`hot_score`),
  KEY `idx_influence_index` (`influence_index`),
  KEY `idx_last_active_time` (`last_active_time`),
  KEY `idx_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博主主表'
; 