-- 博主申请表
CREATE TABLE `artist_application` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '申请ID（自增主键）',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '最后更新时间',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `application_type` varchar(32) NOT NULL COMMENT '申请类型（PERSONAL个人，ORGANIZATION机构，BRAND品牌，MEDIA媒体，KOL，PROFESSIONAL专业）',
  `status` varchar(32) NOT NULL DEFAULT 'APPLYING' COMMENT '申请状态（APPLYING申请中，REVIEWING审核中，ACTIVE已通过，REJECTED审核拒绝，SUSPENDED暂停审核）',
  `artist_name` varchar(128) NOT NULL COMMENT '申请的博主名称',
  `bio` text COMMENT '申请简介',
  `categories` text COMMENT '申请分类（JSON格式）',
  `apply_reason` text NOT NULL COMMENT '申请理由',
  `resume` text COMMENT '个人简历/机构介绍',
  `portfolio_url` varchar(512) COMMENT '作品集链接',
  `social_proof` text COMMENT '社交媒体证明',
  `identity_proof` varchar(512) COMMENT '身份证明文件',
  `qualification_proof` varchar(512) COMMENT '资质证明文件',
  `contact_email` varchar(128) NOT NULL COMMENT '联系邮箱',
  `contact_phone` varchar(32) NOT NULL COMMENT '联系电话',
  `expected_collaboration` text COMMENT '期望合作类型',
  `followers_proof` varchar(512) COMMENT '粉丝数量证明',
  `reviewer_id` bigint unsigned DEFAULT NULL COMMENT '审核员ID',
  `reviewer_name` varchar(64) DEFAULT NULL COMMENT '审核员姓名',
  `review_result` varchar(32) DEFAULT NULL COMMENT '审核结果（APPROVED通过，REJECTED拒绝，NEED_SUPPLEMENT需补充材料，SUSPENDED暂停，RE_REVIEW重新审核）',
  `review_comment` text COMMENT '审核意见',
  `review_score` int DEFAULT NULL COMMENT '审核评分（1-10分）',
  `risk_assessment` text COMMENT '风险评估',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `submit_time` datetime DEFAULT NULL COMMENT '申请提交时间',
  `application_round` int DEFAULT 1 COMMENT '申请轮次（支持重新申请）',
  `ext_info` text COMMENT '扩展信息（JSON格式）',
  `deleted` int DEFAULT 0 COMMENT '是否逻辑删除，0为未删除，非0为已删除',
  `lock_version` int DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_application_type` (`application_type`),
  KEY `idx_status` (`status`),
  KEY `idx_reviewer_id` (`reviewer_id`),
  KEY `idx_review_result` (`review_result`),
  KEY `idx_submit_time` (`submit_time`),
  KEY `idx_review_time` (`review_time`),
  KEY `idx_application_round` (`application_round`),
  KEY `idx_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博主申请表'
; 