-- 博主统计表
CREATE TABLE `artist_statistics` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '统计ID（自增主键）',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '最后更新时间',
  `artist_id` bigint unsigned NOT NULL COMMENT '博主ID',
  `today_followers_growth` int DEFAULT 0 COMMENT '粉丝增长数（今日）',
  `week_followers_growth` int DEFAULT 0 COMMENT '粉丝增长数（本周）',
  `month_followers_growth` int DEFAULT 0 COMMENT '粉丝增长数（本月）',
  `today_works_count` int DEFAULT 0 COMMENT '作品发布数（今日）',
  `week_works_count` int DEFAULT 0 COMMENT '作品发布数（本周）',
  `month_works_count` int DEFAULT 0 COMMENT '作品发布数（本月）',
  `today_likes` bigint DEFAULT 0 COMMENT '获赞数（今日）',
  `week_likes` bigint DEFAULT 0 COMMENT '获赞数（本周）',
  `month_likes` bigint DEFAULT 0 COMMENT '获赞数（本月）',
  `today_views` bigint DEFAULT 0 COMMENT '浏览量（今日）',
  `week_views` bigint DEFAULT 0 COMMENT '浏览量（本周）',
  `month_views` bigint DEFAULT 0 COMMENT '浏览量（本月）',
  `engagement_rate` decimal(5,4) DEFAULT 0.0000 COMMENT '互动率（点赞+评论+分享/浏览量）',
  `followers_activity` decimal(5,4) DEFAULT 0.0000 COMMENT '粉丝活跃度',
  `content_quality_score` decimal(5,4) DEFAULT 0.0000 COMMENT '内容质量分数',
  `influence_index` decimal(10,4) DEFAULT 0.0000 COMMENT '影响力指数',
  `followers_growth_trend` text COMMENT '粉丝增长趋势（JSON格式，近30天每日数据）',
  `content_publish_trend` text COMMENT '内容发布趋势（JSON格式，近30天每日数据）',
  `engagement_trend` text COMMENT '互动数据趋势（JSON格式，近30天每日数据）',
  `popular_tags` text COMMENT '热门标签（JSON格式）',
  `followers_age_distribution` text COMMENT '粉丝年龄分布（JSON格式）',
  `followers_gender_distribution` text COMMENT '粉丝性别分布（JSON格式）',
  `followers_region_distribution` text COMMENT '粉丝地区分布（JSON格式）',
  `best_publish_time` varchar(64) COMMENT '最佳发布时间',
  `avg_engagement_time` int DEFAULT 0 COMMENT '平均互动时间（分钟）',
  `period_start` date NOT NULL COMMENT '统计周期开始时间',
  `period_end` date NOT NULL COMMENT '统计周期结束时间',
  `last_updated` datetime DEFAULT NULL COMMENT '最后更新时间',
  `deleted` int DEFAULT 0 COMMENT '是否逻辑删除，0为未删除，非0为已删除',
  `lock_version` int DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_artist_period` (`artist_id`, `period_start`, `period_end`, `deleted`),
  KEY `idx_artist_id` (`artist_id`),
  KEY `idx_today_followers_growth` (`today_followers_growth`),
  KEY `idx_engagement_rate` (`engagement_rate`),
  KEY `idx_influence_index` (`influence_index`),
  KEY `idx_period_start` (`period_start`),
  KEY `idx_period_end` (`period_end`),
  KEY `idx_last_updated` (`last_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博主统计表'
; 