-- 博主认证表
CREATE TABLE `artist_verification` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '认证ID（自增主键）',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '最后更新时间',
  `artist_id` bigint unsigned NOT NULL COMMENT '博主ID',
  `verification_type` varchar(64) NOT NULL COMMENT '认证类型（PERSONAL个人认证，ORGANIZATION机构认证，PROFESSIONAL专业认证，BLUE_V蓝V认证，GOLD_V金V认证）',
  `status` varchar(32) NOT NULL DEFAULT 'APPLYING' COMMENT '认证状态（APPLYING申请中，REVIEWING审核中，APPROVED已通过，REJECTED已拒绝，EXPIRED已过期，REVOKED已撤销）',
  `verification_desc` varchar(256) COMMENT '认证说明',
  `verification_proof` text COMMENT '认证证明材料',
  `apply_reason` text COMMENT '申请理由',
  `reviewer_id` bigint unsigned DEFAULT NULL COMMENT '审核员ID',
  `reviewer_name` varchar(64) DEFAULT NULL COMMENT '审核员姓名',
  `review_comment` text COMMENT '审核意见',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `apply_time` datetime DEFAULT NULL COMMENT '申请时间',
  `approve_time` datetime DEFAULT NULL COMMENT '通过时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `verification_badge` varchar(128) COMMENT '认证徽章',
  `verification_level` int DEFAULT 1 COMMENT '认证级别（1-5级）',
  `ext_info` text COMMENT '扩展信息（JSON格式）',
  `deleted` int DEFAULT 0 COMMENT '是否逻辑删除，0为未删除，非0为已删除',
  `lock_version` int DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_artist_id` (`artist_id`),
  KEY `idx_verification_type` (`verification_type`),
  KEY `idx_status` (`status`),
  KEY `idx_reviewer_id` (`reviewer_id`),
  KEY `idx_apply_time` (`apply_time`),
  KEY `idx_approve_time` (`approve_time`),
  KEY `idx_expire_time` (`expire_time`),
  KEY `idx_verification_level` (`verification_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博主认证表'
; 