spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9613

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.tag.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 标签模块专用配置
collide:
  tag:
    # 标签名称最大长度
    max-name-length: 20
    # 标签描述最大长度
    max-description-length: 200
    # 热门标签阈值
    hot-threshold: 100
    # 用户兴趣标签最大数量
    max-interest-tags: 50
    # 内容标签最大数量
    max-content-tags: 10
    # 标签推荐开关
    recommendation-enabled: true 