spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
  oss:
    enabled: true
    bucket: mds
    endPoint: http://192.168.1.107:9000
    accessKey: minioadmin
    accessSecret: minioadmin

server:
  port: 9603

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.comment.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 日志配置
logging:
  level:
    com.gig.collide.comment: DEBUG
    org.springframework: INFO
    com.baomidou.mybatisplus: DEBUG

# 评论模块专用配置
collide:
  comment:
    # 最大评论层级深度
    max-depth: 10
    # 评论内容最大长度
    max-content-length: 1000
    # 热门评论阈值（点赞数）
    hot-threshold: 50
    # 敏感词过滤开关
    sensitive-word-filter: true
    # 评论审核开关
    review-enabled: false 