spring:
  elasticsearch:
    enable: ${collide.turbo.elasticsearch.enable}
    uris: http://${collide.turbo.elasticsearch.url}
    username: ${collide.turbo.elasticsearch.username}
    password: ${collide.turbo.elasticsearch.password}
easy-es:
  enable: ${collide.turbo.elasticsearch.enable}
  address : ${collide.turbo.elasticsearch.url}
  username: ${collide.turbo.elasticsearch.username}
  password: ${collide.turbo.elasticsearch.password}