spring:
  application:
    name: @application.name@

# 服务端口配置
server:
  port: 9503
  servlet:
    context-path: /goods
  tomcat:
    threads:
      max: 200
      min-spare: 10

# Dubbo 端口配置 (应用特定)
dubbo:
  protocol:
    port: 20883

# MyBatis Plus 配置 (应用特定)
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gig.collide.goods.domain.entity

# 业务配置 (商品模块特定)
collide:
  goods:
    # 库存相关配置
    stock:
      low-threshold: 10          # 低库存阈值
      alert-enabled: true        # 是否启用库存预警
      auto-off-sale: false       # 是否自动下架库存为0的商品
    
    # 缓存配置
    cache:
      enabled: true
      ttl: 3600                  # 缓存过期时间（秒）
      goods-detail-ttl: 1800     # 商品详情缓存时间
      goods-list-ttl: 600        # 商品列表缓存时间
      hot-goods-ttl: 300         # 热门商品缓存时间
    
    # 分页配置
    page:
      default-size: 20           # 默认分页大小
      max-size: 100              # 最大分页大小
    
    # 幂等性配置
    idempotent:
      enabled: true
      key-prefix: "goods:idempotent:"
      ttl: 300                   # 幂等键过期时间（秒）

# 监控配置 (应用特定)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# 日志配置 (应用特定) 
logging:
  level:
    com.gig.collide.goods: DEBUG
    com.gig.collide.goods.infrastructure.mapper: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

---
# 本地开发环境
spring:
  config:
    activate:
      on-profile: local

server:
  port: 9503

logging:
  level:
    root: INFO
    com.gig.collide.goods: DEBUG

---
# Docker 环境
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

logging:
  level:
    root: INFO
    com.gig.collide.goods: INFO

---
# 生产环境
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080

logging:
  level:
    root: WARN
    com.gig.collide.goods: INFO 