spring:
  cloud:
    sentinel:
      transport:
        dashboard: ${nft.turbo.sentinel.url}
        port: ${nft.turbo.sentinel.port}
      datasource:
        ds:
          nacos:
            server-addr: 192.168.14.129:8848
            data-id:  ${nft.turbo.sentinel.nacos.data-id}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow  # 也可以是 degrade, param-flow, etc.