spring:
  cloud:
    sentinel:
      transport:
        dashboard: ${collide.turbo.sentinel.url}
        port: ${collide.turbo.sentinel.port}
      datasource:
        ds:
          nacos:
            server-addr: ${collide.turbo.nacos.server.url}
            data-id:  ${collide.turbo.sentinel.nacos.data-id}
            group-id: DEFAULT_GROUP
            username: ${collide.turbo.nacos.server.username}
            password: ${collide.turbo.nacos.server.password}
            data-type: json
            rule-type: flow  # 也可以是 degrade, param-flow, etc.